### ISSUE TITLE
Poem is crashed on my Machine

### ISSUE THREAD

**Issue by vrnpwr-dev** [vrnpwr/my-story#4]
Hello @vrnpwr  I am facing some issue. When I open this repo on my machine it crashed.
Hope you find this issue 
Thanks and regards 
<h3>varun Pawar

**Comment by vrnpwr** [comment]
I think you need to reinstall this poem.
Thnaks

**Comment by vrnpwr-dev** [comment]
@vrnpwr Thanks it works for me
